### ISSUE TITLE
Support for replacing parts of a readme

### ISSUE THREAD

**Issue by Gerrit0** [krisztianb/typedoc-plugin-replace-in-comments#2]
A recent request on the typedoc repo indicated it would be nice to be able to replace parts of the readme, which seemed appropriate for this plugin.

Ref: https://github.com/TypeStrong/typedoc/issues/1904

**Comment by glensc** [comment]
If it replaces in any file the plugin should be renamed accordingly too as it's no longer replacing in just comments.

**Comment by krisztianb** [comment]
I'd like to make this optional as some users might not want their replacements applied on other parts of the documentation.

This means that I have to rework how the plugin is configured.

Renaming the plugin makes sense but is not possible on NPM. So it all boils down to deprecating this plugin in favour of another one.

**Comment by glensc** [comment]
yeah, you can rename git repo, but npm just leave abandoned

**Comment by krisztianb** [comment]
What other parts of the documentation would you also replace text in?

Currently the plugin would do this for:

* Code comments
* README.md

**Comment by glensc** [comment]
I don't currently plan replace other than `[[TOC]]`.

Un fact, for my problem, I created a separate readme because typedoc inability to render markdown:
- https://github.com/TypeStrong/typedoc/issues/1906

**Comment by krisztianb** [comment]
I understand. It was more like a general question. So that I can make the new plugin even more useful.

**Comment by glensc** [comment]
Sorry, I'm unable to give you any useful feedback. I'm new to typedoc project and neither I know what are the choices, i.e how the plugin system works.

The broad answer would be: replace everywhere everything ;)

**Comment by krisztianb** [comment]
New plugin is released: https://www.npmjs.com/package/typedoc-plugin-replace-text

If you only want to remove `[[[TOC]]]` from your README and do nothing else. This config should do the job:

```json
"replaceText": {
    "inCodeCommentText": false,
    "inCodeCommentTags": false,
    "inIncludedFiles": true,
    "replacements": [
        {
            "pattern": "\\[\\[\\[TOC\\]\\]\\]",
            "replace": ""
        }
    ]
}
```

**Comment by glensc** [comment]
super! 

btw, it's `[[TOC]]` not `[[[TOC]]]`.
